### ISSUE TITLE
Fails to make

### ISSUE THREAD

**Issue by ygxxz** [microsoft/APSI#10]
[ 90%] Linking CXX executable bin/sender_cli
CMakeFiles/common_cli.dir/cli/common/common_utils.cpp.o: In function `throw_if_file_invalid(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
common_utils.cpp:(.text+0x60e): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
common_utils.cpp:(.text+0x616): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
common_utils.cpp:(.text+0x784): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/sender_cli.dir/build.make:132: recipe for target 'bin/sender_cli' failed
make[2]: *** [bin/sender_cli] Error 1
CMakeFiles/Makefile2:646: recipe for target 'CMakeFiles/sender_cli.dir/all' failed
make[1]: *** [CMakeFiles/sender_cli.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by kimlaine** [comment]
It seems you don’t have the C++ standard filesystem library available or installed but it’s hard to say why. Are you using g++ or clang++?
