### ISSUE TITLE
Can I use APSI through python call c++?

### ISSUE THREAD

**Issue by clearlovel7** [microsoft/APSI#13]
I want use APSI in a python project.
Is it feasible to call C++ with python to use APSI?

**Comment by kimlaine** [comment]
No -- you would need to build a wrapper layer somehow, for example, by using [pybind11](https://pybind11.readthedocs.io/en/stable/). This would be pretty easy but maybe a bit tedious if you want to cover the entire APSI API. If you, or someone else, would want to do it, it would certainly be greatly appreciated. :)

**Comment by clearlovel7** [comment]
Ok.I will try to use pybind11.
Thank you for your suggestion ！

**Comment by LGro** [comment]
@clearlovel7, did you ever get into wrapping APSI for Python?
