### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by autoantwort** [microsoft/APSI#15]
Does this lib support arm64? 

https://github.com/microsoft/APSI/blob/39b45ceff89ca07d0e9481fac894252765989fcc/common/apsi/fourq/CMakeLists.txt#L29-L30

You add a sub folder `arm64`, but there is no sub folder `arm64`. 

From https://github.com/microsoft/vcpkg/pull/23034#discussion_r805106335

**Comment by kimlaine** [comment]
Those directories are only for accelerating FourQlib on specific platforms. The generic code should work anyway.

**Comment by autoantwort** [comment]
But cmake failed because of that. When I try to build the lib on my mac I get the following:
```
CMake Error at common/apsi/fourq/CMakeLists.txt:30 (add_subdirectory):
  add_subdirectory given source "arm64" which is not an existing directory.
```

**Comment by kimlaine** [comment]
I see. Let me take a look at this to see what we were intending to do here. Thanks for the report!

**Comment by kiromaru** [comment]
Thank you for reporting this. We have committed a fix that should fix this issue.
