### ISSUE TITLE
Error？

### ISSUE THREAD

**Issue by Hang-shao** [microsoft/APSI#16]
Lowering the Depth

The first step towards making this naive idea practical is to figure out ways of lowering the multiplicative depth of the computation. First, notice that the **sender can split up its set into S equally sized parts and evaluate the matching polynomial independently on each of the parts**, producing S results {M_i(Q)}. **All of these results must be sent back to the receiver,** so the sender-to-receiver communication has increased by a factor of S. Nevertheless, this turns out to be a really valuable trick in helping reduce the size of the encryption parameters.

Shouldn't it be a receiver split?
Shouldn't the receiver send it to the sender?
 receiver-》sender？

**Comment by kimlaine** [comment]
No, I think the text here is correct. The Sender splits its (large) dataset. The Receiver sends an encrypted query to the Sender, and that query is evaluated independently against each of the Sender's dataset parts. Each produces an independent result, which are all sent back to the Receiver for decryption.

**Comment by Hang-shao** [comment]
> No, I think the text here is correct. The Sender splits its (large) dataset. The Receiver sends an encrypted query to the Sender, and that query is evaluated independently against each of the Sender's dataset parts. Each produces an independent result, which are all sent back to the Receiver for decryption.

Thank you for your reply. I understand
