### ISSUE TITLE
Build error On Windows 11 

### ISSUE THREAD

**Issue by FearlessSong** [microsoft/APSI#18]
I want to build the test by the clion , i add the cmake options `-DCMAKE_TOOLCHAIN_FILE=D:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET="x64-windows-static-md"`
However , the errors occur.

> "D:\Program Files\JetBrains\CLion 2021.3.3\bin\cmake\win\bin\cmake.exe" --build C:\Users\69424\Desktop\APSI-main\cmake-build-debug --target apsi
[1/29] Building C object CMakeFiles/apsi.dir/common/apsi/fourq/crypto_util.c.obj
FAILED: CMakeFiles/apsi.dir/common/apsi/fourq/crypto_util.c.obj 
D:\PROGRA~2\JETBRA~1\CLION2~1.3\bin\mingw\bin\gcc.exe -DZMQ_STATIC -IC:/Users/69424/Desktop/APSI-main/common -IC:/Users/69424/Desktop/APSI-main/sender -IC:/Users/69424/Desktop/APSI-main/receiver -IC:/Users/69424/Desktop/APSI-main/cmake-build-debug/common -IC:/Users/69424/Desktop/APSI-main/cmake-build-debug/sender -isystem D:/vcpkg/installed/x64-windows-static-md/include/SEAL-3.7 -isystem D:/vcpkg/installed/x64-windows-static-md/include -isystem D:/vcpkg/installed/x64-windows-static-md/include/Kuku-2.1 -g -DHAVE_CONFIG -DUSE_SECURE_SEED -DUSE_ENDO=true -D_AMD64_ -march=native -mavx2 -D_AVX2_ -MD -MT CMakeFiles/apsi.dir/common/apsi/fourq/crypto_util.c.obj -MF CMakeFiles\apsi.dir\common\apsi\fourq\crypto_util.c.obj.d -o CMakeFiles/apsi.dir/common/apsi/fourq/crypto_util.c.obj -c C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/crypto_util.c
In file included from C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/FourQ_api.h:22,
                 from C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/FourQ_internal.h:22,
                 from C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/crypto_util.c:9:
C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/FourQ.h:36:2: error: #error -- "Unsupported OS"
   36 | #error-- "Unsupported OS"
      |  ^~~~~
In file included from C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/crypto_util.c:9:
C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/FourQ_internal.h:40:2: error: #error -- "Unsupported configuration"
   40 | #error-- "Unsupported configuration"
      |  ^~~~~
C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/crypto_util.c: In function 'Montgomery_inversion_mod_order':
C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/crypto_util.c:188:17: warning: implicit declaration of function 'SHIFTL' [-Wimplicit-function-declaration]
  188 |                 SHIFTL(modulus2[j], modulus2[j - 1], 1, modulus2[j], RADIX);
      |                 ^~~~~~
[2/29] Building C object CMakeFiles/apsi.dir/common/apsi/fourq/eccp2_no_endo.c.obj
FAILED: CMakeFiles/apsi.dir/common/apsi/fourq/eccp2_no_endo.c.obj 
D:\PROGRA~2\JETBRA~1\CLION2~1.3\bin\mingw\bin\gcc.exe -DZMQ_STATIC -IC:/Users/69424/Desktop/APSI-main/common -IC:/Users/69424/Desktop/APSI-main/sender -IC:/Users/69424/Desktop/APSI-main/receiver -IC:/Users/69424/Desktop/APSI-main/cmake-build-debug/common -IC:/Users/69424/Desktop/APSI-main/cmake-build-debug/sender -isystem D:/vcpkg/installed/x64-windows-static-md/include/SEAL-3.7 -isystem D:/vcpkg/installed/x64-windows-static-md/include -isystem D:/vcpkg/installed/x64-windows-static-md/include/Kuku-2.1 -g -DHAVE_CONFIG -DUSE_SECURE_SEED -DUSE_ENDO=true -D_AMD64_ -march=native -mavx2 -D_AVX2_ -MD -MT CMakeFiles/apsi.dir/common/apsi/fourq/eccp2_no_endo.c.obj -MF CMakeFiles\apsi.dir\common\apsi\fourq\eccp2_no_endo.c.obj.d -o CMakeFiles/apsi.dir/common/apsi/fourq/eccp2_no_endo.c.obj -c C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/eccp2_no_endo.c
In file included from C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/FourQ_api.h:22,
                 from C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/FourQ_internal.h:22,
                 from C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/eccp2_no_endo.c:14:
C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/FourQ.h:36:2: **error: #error -- "Unsupported OS"**
   36 | #error-- "Unsupported OS"
      |  ^~~~~
In file included from C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/eccp2_no_endo.c:14:
C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/FourQ_internal.h:40:2: error: **#error -- "Unsupported configuration"**
   40 | #error-- "Unsupported configuration"
      |  ^~~~~
[3/29] Building C object CMakeFiles/apsi.dir/common/apsi/fourq/eccp2.c.obj
FAILED: CMakeFiles/apsi.dir/common/apsi/fourq/eccp2.c.obj 
D:\PROGRA~2\JETBRA~1\CLION2~1.3\bin\mingw\bin\gcc.exe -DZMQ_STATIC -IC:/Users/69424/Desktop/APSI-main/common -IC:/Users/69424/Desktop/APSI-main/sender -IC:/Users/69424/Desktop/APSI-main/receiver -IC:/Users/69424/Desktop/APSI-main/cmake-build-debug/common -IC:/Users/69424/Desktop/APSI-main/cmake-build-debug/sender -isystem D:/vcpkg/installed/x64-windows-static-md/include/SEAL-3.7 -isystem D:/vcpkg/installed/x64-windows-static-md/include -isystem D:/vcpkg/installed/x64-windows-static-md/include/Kuku-2.1 -g -DHAVE_CONFIG -DUSE_SECURE_SEED -DUSE_ENDO=true -D_AMD64_ -march=native -mavx2 -D_AVX2_ -MD -MT CMakeFiles/apsi.dir/common/apsi/fourq/eccp2.c.obj -MF CMakeFiles\apsi.dir\common\apsi\fourq\eccp2.c.obj.d -o CMakeFiles/apsi.dir/common/apsi/fourq/eccp2.c.obj -c C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/eccp2.c
In file included from C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/FourQ_api.h:22,
                 from C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/FourQ_internal.h:22,
                 from C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/eccp2.c:14:
C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/FourQ.h:36:2: **error: #error -- "Unsupported OS"**
   36 | #error-- "Unsupported OS"
      |  ^~~~~
In file included from C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/eccp2.c:14:
C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/FourQ_internal.h:40:2: error: **#error -- "Unsupported configuration"**
   40 | #error-- "Unsupported configuration"
      |  ^~~~~
C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/eccp2.c: In function 'mul_truncate':
C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/eccp2.c:208:5: error: unknown type name 'uint128_t'; did you mean 'uint32_t'?
  208 |     uint128_t tt1, tt2;
      |     ^~~~~~~~~
      |     uint32_t
[4/29] Building C object CMakeFiles/apsi.dir/common/apsi/fourq/hash_to_curve.c.obj
FAILED: CMakeFiles/apsi.dir/common/apsi/fourq/hash_to_curve.c.obj 
D:\PROGRA~2\JETBRA~1\CLION2~1.3\bin\mingw\bin\gcc.exe -DZMQ_STATIC -IC:/Users/69424/Desktop/APSI-main/common -IC:/Users/69424/Desktop/APSI-main/sender -IC:/Users/69424/Desktop/APSI-main/receiver -IC:/Users/69424/Desktop/APSI-main/cmake-build-debug/common -IC:/Users/69424/Desktop/APSI-main/cmake-build-debug/sender -isystem D:/vcpkg/installed/x64-windows-static-md/include/SEAL-3.7 -isystem D:/vcpkg/installed/x64-windows-static-md/include -isystem D:/vcpkg/installed/x64-windows-static-md/include/Kuku-2.1 -g -DHAVE_CONFIG -DUSE_SECURE_SEED -DUSE_ENDO=true -D_AMD64_ -march=native -mavx2 -D_AVX2_ -MD -MT CMakeFiles/apsi.dir/common/apsi/fourq/hash_to_curve.c.obj -MF CMakeFiles\apsi.dir\common\apsi\fourq\hash_to_curve.c.obj.d -o CMakeFiles/apsi.dir/common/apsi/fourq/hash_to_curve.c.obj -c C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/hash_to_curve.c
In file included from C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/FourQ_api.h:22,
                 from C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/FourQ_internal.h:22,
                 from C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/hash_to_curve.c:9:
C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/FourQ.h:36:2: error: #error -- "Unsupported OS"
   36 | #error-- "Unsupported OS"
      |  ^~~~~
In file included from C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/hash_to_curve.c:9:
C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/FourQ_internal.h:40:2: error: #error -- "Unsupported configuration"
   40 | #error-- "Unsupported configuration"
      |  ^~~~~
[5/29] Building C object CMakeFiles/apsi.dir/common/apsi/fourq/random.c.obj
[6/29] Building C object CMakeFiles/apsi.dir/common/apsi/fourq/eccp2_core.c.obj
FAILED: CMakeFiles/apsi.dir/common/apsi/fourq/eccp2_core.c.obj 
D:\PROGRA~2\JETBRA~1\CLION2~1.3\bin\mingw\bin\gcc.exe -DZMQ_STATIC -IC:/Users/69424/Desktop/APSI-main/common -IC:/Users/69424/Desktop/APSI-main/sender -IC:/Users/69424/Desktop/APSI-main/receiver -IC:/Users/69424/Desktop/APSI-main/cmake-build-debug/common -IC:/Users/69424/Desktop/APSI-main/cmake-build-debug/sender -isystem D:/vcpkg/installed/x64-windows-static-md/include/SEAL-3.7 -isystem D:/vcpkg/installed/x64-windows-static-md/include -isystem D:/vcpkg/installed/x64-windows-static-md/include/Kuku-2.1 -g -DHAVE_CONFIG -DUSE_SECURE_SEED -DUSE_ENDO=true -D_AMD64_ -march=native -mavx2 -D_AVX2_ -MD -MT CMakeFiles/apsi.dir/common/apsi/fourq/eccp2_core.c.obj -MF CMakeFiles\apsi.dir\common\apsi\fourq\eccp2_core.c.obj.d -o CMakeFiles/apsi.dir/common/apsi/fourq/eccp2_core.c.obj -c C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/eccp2_core.c
In file included from C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/FourQ_api.h:22,
                 from C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/FourQ_internal.h:22,
                 from C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/eccp2_core.c:14:
C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/FourQ.h:36:2: error: #error -- "Unsupported OS"
   36 | #error-- "Unsupported OS"
      |  ^~~~~
In file included from C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/eccp2_core.c:14:
C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/FourQ_internal.h:40:2: error: #error -- "Unsupported configuration"
   40 | #error-- "Unsupported configuration"
      |  ^~~~~
In file included from C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/eccp2_core.c:20:
C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/amd64/fp_x64.h: In function 'fpmul1271':
C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/amd64/fp_x64.h:122:5: **error: unknown type name 'uint128_t'; did you mean 'uint32_t'?**
  122 |     uint128_t tt1, tt2, tt3 = { 0 };
      |     ^~~~~~~~~
      |     uint32_t
C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/amd64/fp_x64.h: In function 'fpsqr1271':
C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/amd64/fp_x64.h:157:5: **error: unknown type name 'uint128_t'; did you mean 'uint32_t'?**
  157 |     uint128_t tt1, tt2, tt3 = { 0 };
      |     ^~~~~~~~~
      |     uint32_t
C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/amd64/fp_x64.h: In function 'multiply':
C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/amd64/fp_x64.h:255:13: warning: implicit declaration of function 'MUL' [-Wimplicit-function-declaration]
  255 |             MUL(a[i], b[j], UV + 1, UV[0]);
      |             ^~~
C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/amd64/fp_x64.h:256:13: warning: implicit declaration of function 'ADDC' [-Wimplicit-function-declaration]
  256 |             ADDC(0, UV[0], u, carry, v);
      |             ^~~~
C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/amd64/fp_x64.h: In function 'subtract':
C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/amd64/fp_x64.h:284:9: warning: implicit declaration of function 'SUBC' [-Wimplicit-function-declaration]
  284 |         SUBC(borrow, a[i], b[i], borrow, c[i]);
      |         ^~~~
C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/amd64/fp_x64.h: In function 'fpdiv1271':
C:/Users/69424/Desktop/APSI-main/common/apsi/fourq/amd64/fp_x64.h:377:5: warning: implicit declaration of function 'SHIFTR' [-Wimplicit-function-declaration]
  377 |     SHIFTR(temp[1], temp[0], 1, a[0], RADIX);
      |     ^~~~~~
[7/29] Building CXX object CMakeFiles/apsi.dir/common/apsi/network/sender_operation_response.cpp.obj
[8/29] Building CXX object CMakeFiles/apsi.dir/common/apsi/network/result_package.cpp.obj
[9/29] Building CXX object CMakeFiles/apsi.dir/common/apsi/network/sender_operation.cpp.obj
[10/29] Building CXX object CMakeFiles/apsi.dir/common/apsi/network/zmq/zmq_channel.cpp.obj
ninja: build stopped: subcommand failed.

In a Word, when it refers to "**#error**" or "**uint128_t**", the build will fail. Someone in the internet says something is wrong about my GCC.
>gcc --version
gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

**Comment by HelmetOff** [comment]
How did you solve it?

**Comment by FearlessSong** [comment]
> How did you solve it?

I remeber that I built the vcpkg on the Visual studio 2022
