### ISSUE TITLE
Visual studio build error 

### ISSUE THREAD

**Issue by FearlessSong** [microsoft/APSI#19]
i have installed the APSI by vcpkg, and run `.\vcpkg.exe  integrate install ` commend .
Cmake successed. However, the processing of building fail.
![capture_20220316124217095](https://user-images.githubusercontent.com/26964688/158518259-9a33731d-2d16-4de9-b0b8-c9a9e802a09b.jpg)
Thanks for your help!!!!!

**Comment by WeiDaiWD** [comment]
> i have installed the APSI by vcpkg

Why are you building APSI after having installed APSI?

Also the line numbers in error messages do not match with the latest APSI source files. For example, `bit_buf` do not appear on line 291 or 313 in db_encoding.cpp. I'm not clear what you were building.

**Comment by FearlessSong** [comment]
> > i have installed the APSI by vcpkg
> 
> Why are you building APSI after having installed APSI?
> 
> Also the line numbers in error messages do not match with the latest APSI source files. For example, `bit_buf` do not appear on line 291 or 313 in db_encoding.cpp. I'm not clear what you were building.

because i want to run the test.
