### ISSUE TITLE
A question of the code

### ISSUE THREAD

**Issue by xie123321** [microsoft/APSI#21]
Is there a problem with the judgment condition here(sender\apsi\senderdb.cpp:row 1202) ?
<img width="706" alt="code" src="https://user-images.githubusercontent.com/82272372/160235553-08d24118-3917-40dc-9daf-fd7fcbbc46c5.png">

**Comment by kimlaine** [comment]
Thanks for pointing this out! I'll push an update right away (v0.8.0).
