### ISSUE TITLE
If the receiver holds 100,000 items, how to set the parameters?

### ISSUE THREAD

**Issue by BeStrongok** [microsoft/APSI#23]
hello, when the receiver holds 100,000 items, the parameters i set are:
`{
    "table_params": {
        "hash_func_count": 3,
        "table_size": 100000,
        "max_items_per_bin": 4000
    },
    "item_params": {
        "felts_per_item": 4
    },
    "query_params": {
        "ps_low_degree": 310,
        "query_powers": [ 1, 4, 10, 11, 28, 33, 78, 118, 143, 311, 1555]
    },
    "seal_params": {
        "plain_modulus_bits": 26,
        "poly_modulus_degree": 400000,
        "coeff_modulus_bits": [ 50, 50, 50, 38, 30 ]
    }
}`
And the code throw an ERROR: poly_modulus_degree is invalid, i find that SEAL set SEAL_POLY_MOD_DEGREE_MAX=131072. How to set the parameters in this case?

**Comment by rnjailamba** [comment]
@BeStrongok what parameters did you finally use for 100K receiver items. Also did you find any upper bound of number of receiver elements for efficient PSI with APSI?
