### ISSUE TITLE
Force AVX even when AVX2 available

### ISSUE THREAD

**Issue by LGro** [microsoft/APSI#25]
It seems that when the build system's CPU supports AVX2 it is [always used for FourQ](https://github.com/microsoft/APSI/blob/main/common/apsi/fourq/FourQ.h#L106-L112). I'm currently facing compiler errors in a downstream application including APSI for AVX2 enabled systems where for systems that only support AVX everything works. Is there already an option or would you consider adding one to enforce AVX even if AVX2 support is available (e.g. a `-D_NO_AVX2_=1` option)?
Beyond my current build issue I'm also thinking about if and how pre-built libraries could be distributed as part of a package in a robust way so that even if the package is built on an AVX2 enabled system, it could still be used on systems that share the same OS and architecture but only support AVX.

**Comment by kiromaru** [comment]
This has been fixed in the latest release, version 0.8.2.
You are now able to specify -DAPSI_DETECT_AVX=OFF and/or -DAPSI_DETECT_AVX2=OFF to turn off AVX detection (ON by default).
