### ISSUE TITLE
Failed to compile apsi on arm64 machine

### ISSUE THREAD

**Issue by BeStrongok** [microsoft/APSI#28]
When i compile the latest source code, there was an error:
`
[ 97%] Linking CXX executable bin/receiver_cli
/usr/bin/ld: lib/libapsi-0.8.a(eccp2_core.c.o): in function `fp2sqr1271':
eccp2_core.c:(.text+0x1504): undefined reference to `fp2sqr1271_a'
/usr/bin/ld: lib/libapsi-0.8.a(eccp2_core.c.o): in function `fp2mul1271':
eccp2_core.c:(.text+0x1510): undefined reference to `fp2mul1271_a'
/usr/bin/ld: lib/libapsi-0.8.a(eccp2_core.c.o): in function `eccdouble':
eccp2_core.c:(.text+0x1afc): undefined reference to `fp2addsub1271_a'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/receiver_cli.dir/build.make:112: bin/receiver_cli] Error 1
make[1]: *** [CMakeFiles/Makefile2:428: CMakeFiles/receiver_cli.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX executable bin/sender_cli
/usr/bin/ld: lib/libapsi-0.8.a(eccp2_core.c.o): in function `fp2sqr1271':
eccp2_core.c:(.text+0x1504): undefined reference to `fp2sqr1271_a'
/usr/bin/ld: lib/libapsi-0.8.a(eccp2_core.c.o): in function `fp2mul1271':
eccp2_core.c:(.text+0x1510): undefined reference to `fp2mul1271_a'
/usr/bin/ld: lib/libapsi-0.8.a(eccp2_core.c.o): in function `eccdouble':
eccp2_core.c:(.text+0x1afc): undefined reference to `fp2addsub1271_a'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/sender_cli.dir/build.make:128: bin/sender_cli] Error 1
make[1]: *** [CMakeFiles/Makefile2:401: CMakeFiles/sender_cli.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
`
I don't kown how to fix it, can you help me? It seems that the problem is correlated with the FourQ.

**Comment by kiromaru** [comment]
Hi,

It seems you are compiling on a Linux machine with an arm64 processor, is that correct? This is a configuration we had not tested before.

Please see line 306 of the CMakeLists.txt file: https://github.com/microsoft/APSI/blob/8a0a5cce4f7a1cb2558f33d79ac26c65fb8ece84/CMakeLists.txt#L306

And try to change it to the following:
`if(UNIX AND APSI_FOURQ_AMD64 AND NOT APPLE AND NOT CYGWIN AND NOT MINGW)`

Please let us know if this works for you.

Thank you!

**Comment by kiromaru** [comment]
This has been fixed in version 0.8.2.
