### ISSUE TITLE
APSI as a shared library

### ISSUE THREAD

**Issue by LGro** [microsoft/APSI#29]
When I applied the [instructions](https://github.com/microsoft/vcpkg/blob/master/docs/examples/overlay-triplets-linux-dynamic.md) on how to build a shared library with vcpkg on Linux to APSI (`vcpkg install apsi:x64-linux-dynamic`), I noticed `Error: apsi[core] is only supported on 'static & !(arm & osx)'`

How strict is that limitation? I'm currently trying to wrap APSI in a dynamic library and was wondering if and how it'd be possible to allow building a shared version of APSI.
This is not blocking anything on my end, I'm mostly curious to learn what the implications would be on the APSI side.

**Comment by kimlaine** [comment]
I believe we limited to static builds just to reduce complexity of the build system and to ensure smooth experience in as many environments as possible. There is no reason why APSI couldn't be built as a shared library. What we've preferred to do is build simpler shared libraries on top of (static) APSI that then expose only particular functionality we actually need.

**Comment by LGro** [comment]
Thanks for sharing :relaxed:
