### ISSUE TITLE
Build fails on x86-windows #error: -- "Unsupported ARCHITECTURE"

### ISSUE THREAD

**Issue by Adela0814** [microsoft/APSI#33]
When I build `apsi` using `vcpkg`, I get the following error message. Looks like the macro `_86_` is missing. I want to confirm this needs to be fixed or is it really not supporting x86-windows?

`E:\vcpkg\buildtrees\apsi\src\d48f0a1e6c-9e75655829.clean\common\apsi/fourq/FourQ.h(91): fatal error C1189: #error: -- "Unsupported ARCHITECTURE"`

**Comment by kiromaru** [comment]
Hello,

The library should be able to support x86. This is something that should be fixed.
Thank you for reporting this!

**Comment by kiromaru** [comment]
This has been fixed in the latest release, version 0.8.2.
