### ISSUE TITLE
error occurs when generating dynamic library？

### ISSUE THREAD

**Issue by muou55555** [microsoft/APSI#35]
I try to generate a dynamic library and report the following errors：
```
relocation R_X86_64_PC32 against undefined symbol `ONEx8' can not be used when making a shared object; recompile with -fPIC
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: final link failed: Bad value
```
I found that cmakelist currently only supports static libraries。
When will dynamic libraries be supported or My operations have any error?

**Comment by kimlaine** [comment]
The buildsystem is detecting support for AMD64 specific ASM implementations for some field arithmetic ([these .S files](https://github.com/microsoft/APSI/tree/main/common/apsi/fourq/amd64)). However, the implementations are not compatible with PIC. You can disable them by (cleaning up your build directory) and reconfiguring/building with `-DAPSI_DETECT_AVX=OFF` and `-DAPSI_DETECT_AVX2=OFF`. By doing this, I was able to build a working .so library.

**Comment by muou55555** [comment]
> The buildsystem is detecting support for AMD64 specific ASM implementations for some field arithmetic ([these .S files](https://github.com/microsoft/APSI/tree/main/common/apsi/fourq/amd64)). However, the implementations are not compatible with PIC. You can disable them by (cleaning up your build directory and) reconfiguring/building with `-DAPSI_DETECT_AVX=OFF` and `-DAPSI_DETECT_AVX2=OFF`. By doing this, I was able to build a working .so library.



> The buildsystem is detecting support for AMD64 specific ASM implementations for some field arithmetic ([these .S files](https://github.com/microsoft/APSI/tree/main/common/apsi/fourq/amd64)). However, the implementations are not compatible with PIC. You can disable them by (cleaning up your build directory and) reconfiguring/building with `-DAPSI_DETECT_AVX=OFF` and `-DAPSI_DETECT_AVX2=OFF`. By doing this, I was able to build a working .so library.

thx. I also deal with it in this way and work well. however，how do it supports both avx2 and build a .so library?

**Comment by TY-cc** [comment]
@muou55555 HI, have you generated the dynamic library? I tried to rebuild with `-DAPSI_DETECT_AVX=OFF` and `-DAPSI_DETECT_AVX2=OFF`,  but it tell me `Manually-specified variables were not used by the project` for the `APSI_DETECT_AVX` and `APSI_DETECT_AVX2`
