### ISSUE TITLE
CMake error

### ISSUE THREAD

**Issue by skyer2** [microsoft/APSI#40]
when I try to build and meet that CMake error.  I have already set `cmake ../my/project -DCMAKE_TOOLCHAIN_FILE=[vcpkg-root]/scripts/buildsystems/vcpkg.cmak`
First I meet that "seal.cmake" in CMAKE_MODULE_PATH this project has asked CMake to find a package configuration file provided "SEAL",but CMAKE did not find one. 
Then I set seal's cmakefile in computer environment manually.  
But after that, it still have other problems as following.

![fd4edb75b241c952a4b8202ead06954](https://user-images.githubusercontent.com/48241746/194772173-d2201ad6-b7cf-4d75-bab9-8ba6f8037812.jpg)

It seems that  the vcpkg is not correctly integrated into the cmake in my visual studio2022?
looking foward to  your reply, thx.

**Comment by kimlaine** [comment]
This may be the same problem as [in this Issue](https://github.com/microsoft/APSI/issues/39#issuecomment-1371742263).
