### ISSUE TITLE
Parameters setting of the experiments in paper

### ISSUE THREAD

**Issue by Katherine-101** [microsoft/APSI#41]
![image](https://user-images.githubusercontent.com/106299543/196676886-f7285390-3981-4c95-9c1c-a63c4fd0b5d1.png)
Which set of parameters configuration is used in the experiment in Table 4 of the paper? 

I want to know how to set the parameters when |X| = 1000000, |Y| = 1, label size = 16 / 32 bytes for the best performance.
I tried [parameters/1M-1-32.json](https://github.com/microsoft/APSI/blob/main/parameters/1M-1-32.json), but it doesn't seem to achieve the performance shown in the table.

**Comment by kimlaine** [comment]
I suppose you are talking about runtime. Do you get the correct communication complexity? If so, then at least the parameter setting is correct. Maybe the machine you are running it on is just different?
