### ISSUE TITLE
Issue about the labels cannot be more than 1 KB

### ISSUE THREAD

**Issue by Katherine-101** [microsoft/APSI#44]
Hello! I have a question about the Label Mode.
Why the labels cannot be more than 1 KB? What should I do to make the label support 3KB or more than 3KB? 
Can the current APSI do that? 

![image](https://user-images.githubusercontent.com/106299543/210942707-55a953ba-653d-4247-abf7-85b6b1342264.png)

**Comment by kimlaine** [comment]
There is no fundamental reason for it. If you just comment out the check it will work. My thinking was that it’s going to be really slow to do preprocessing for such labels and the user might not be understanding this. If you have such long labels, you probably should be thinking of other solutions.
