### ISSUE TITLE
flatbuffer related

### ISSUE THREAD

**Issue by kexuedaishu** [microsoft/APSI#46]
The preprocessing stage generates the sender_db file with Flatbuffer. In the online stage, the sender_db must be loaded beforehand and it takes a while for long labels. I am wondering if there is a faster way to read sender_db, maybe saving sender_db with Redis or else?

**Comment by kimlaine** [comment]
That might be a good idea and shouldn't be very hard to do. I think a lot of people would benefit from improved performance in the SenderDB serialization. :)
