### ISSUE TITLE
When building from source, CMake cannot find SEAL version 4

### ISSUE THREAD

**Issue by jtakeshi-nd** [microsoft/APSI#49]
System: Ubuntu 20.04. All dependencies are installed using `vcpkg`, which is installed in my home directory of `/home/jonathan`.
When attempting to build from source in the directory `APSI/cmake`, the command `cmake -DCMAKE_TOOLCHAIN_FILE=/home/jonathan/vcpkg/scripts/buildsystems/vcpkg.cmake ..` indicates that a SEAL version compatible with "4" cannot be found:

`
-- Build type (CMAKE_BUILD_TYPE): Release
-- APSI debug mode: OFF
-- APSI_USE_CXX17: ON
CMake Error at /home/jonathan/vcpkg/scripts/buildsystems/vcpkg.cmake:852 (_find_package):
  Could not find a configuration file for package "SEAL" that is compatible
  with requested version "4".

  The following configuration files were considered but not accepted:

    /home/jonathan/vcpkg/installed/x64-linux/share/seal/SEALConfig.cmake, version: 4.1.1
    /usr/local/lib/cmake/SEAL/SEALConfig.cmake, version: 3.3.1
    /usr/local/lib/cmake/SEAL-4.1/SEALConfig.cmake, version: 4.1.1

Call Stack (most recent call first):
  CMakeLists.txt:120 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/jonathan/DHS/caoe-cerberus/APSI/CMakeFiles/CMakeOutput.log".
`

Changing the version in `/home/jonathan/vcpkg/installed/x64-linux/share/seal/SEALConfig.cmake` from 4.1.1 to 4 did not resolve the issue.

Is there a string I can change to fix this?

**Comment by jtakeshi-nd** [comment]
One workaround is to change the version in CMakeLists.txt to 4.1.1 from 4. This error seems a bit odd, as EXACT isn't specified in CMakeLists.txt's find_package search for SEAL (though I'm not at all a CMake expert).

**Comment by kimlaine** [comment]
Thanks for reporting. This is now fixed.
