### ISSUE TITLE
How to build a test?

### ISSUE THREAD

**Issue by commonye1** [microsoft/APSI#51]
How to build a test after installing all the tools by vcpkg?

**Comment by kimlaine** [comment]
Are you following the instructions [here](https://github.com/microsoft/APSI/blob/main/README.md#building-and-installing-apsi-manually)? You'll need to then configure APSI by specifying the CMake toolchain file (see vcpkg instructions) and remember to use also `-DAPSI_BUILD_TESTS=ON` (and `-DAPSI_BUILD_CLI=ON` if you want to CLI). At which step are you stuck more precisely?
