### ISSUE TITLE
8c16g, how to handle big data. At about 100w, bundle.cache() takes up 17g

### ISSUE THREAD

**Issue by yellow123Nike** [microsoft/APSI#52]
**8c16g, how to handle big data. At about 100w, bundle.cache() takes up 17g**

**Comment by kimlaine** [comment]
Unfortunately, there is a significant cost in encoding a dataset into a `SenderDB` object. This can be somewhat controlled by adjusting the parameters. Another option might be to shard your dataset into smaller parts and then index into those using some mechanism. Of course this leaks some information then about which shard the query lands in. A third option is to get a machine with more RAM.
