### ISSUE TITLE
Error，Could not find a package configuration file provided by "Kuku"

### ISSUE THREAD

**Issue by ZhangChuanxin1** [microsoft/APSI#54]
CMake Error at CMakeLists.txt:131 (find_package):
  By not providing "FindKuku.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Kuku", but
  CMake did not find one.

  Could not find a package configuration file provided by "Kuku" (requested
  version 2.1.0) with any of the following names:

    KukuConfig.cmake
    kuku-config.cmake

  Add the installation prefix of "Kuku" to CMAKE_PREFIX_PATH or set
  "Kuku_DIR" to a directory containing one of the above files.  If "Kuku"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by kimlaine** [comment]
Did you install it with vcpkg as described in the README?

**Comment by zzzzhw** [comment]
Have you resolved this issue? I am encountering the same error.
