### ISSUE TITLE
question on readme

### ISSUE THREAD

**Issue by feng-nvxcloud** [microsoft/APSI#56]
Hi, I just read your the readme the following

"The second trick is to break up each item into multiple parts and encode them separately into consecutive batching slots. Namely, if plain_modulus is a B-bit prime, then we write only B - 1 bits of an item into a batching slot and the next B - 1 bits into the next slot. One downside is that a batched plaintext/ciphertext now only holds a fraction of poly_modulus_degree items. Typically we would use either 4 or 8 slots per item. For example, if plain_modulus is a 20-bit prime, then 4 slots could encode an item of length 80, and the query ciphertext Q (and its powers) can encrypt up to poly_modulus_degree / 4 of the receiver's items. The receiver now queries substantially fewer items than before. The solution is to decouple the cuckoo hash table size from the poly_modulus_degree and simply use two or more ciphertexts to encrypt {X_i} (and their powers)."

It says " B-bit prime, then we write only B - 1 bits of an item into a batching slot and the next B - 1 bits into the next slot", but the example says " if plain_modulus is a 20-bit prime, then 4 slots could encode an item of length 80". Based on the first statement, 20-bit prime can hold up to 19 =20 -1 bit, so for 80 bit item, it should use [80 / 19] = 5 slots instead of 4, right?

Thank you.

**Comment by kimlaine** [comment]
You are absolutely right. I'll update this README right now.
