### ISSUE TITLE
How to choose plain_modulus

### ISSUE THREAD

**Issue by banlandadi** [microsoft/APSI#61]
Hi,I want to know if I choose a n bit plain_modulus as fellowing:
def generate_prime_number(n, polyModulusDegree):
    p = (1 << n)+1
    while True:
        if is_prime(p):
            break
        else:
            p += 2*polyModulusDegree
    return p
 Is this function right?or I need to let p=1<<(n-1)+1 in init phase?
Cause I have noticed in the APSI Params ,you mentioned 65537 is a 16bit prime,but actually it's 0001 0000 0000 0000 0001 ,which is 17 bit at least。
Thank you !

**Comment by kimlaine** [comment]
Thanks for pointing out the typo in the `README.md`. Of course this is a 17-bit prime -- not 16. In your function you probably want to start from p=1<<(n-1)+1.
