### ISSUE TITLE
Global static initializers in 

### ISSUE THREAD

**Issue by chrdavis** [microsoft/APSI#66]
Please move the calls to initialize thread_count and phys_thread_count to a local static where they are first used.  Otherwise these run at startup.

thread_pool_mgr.cpp

namespace {
    mutex tp_mutex;
    size_t thread_count = thread::hardware_concurrency();
    size_t phys_thread_count = thread::hardware_concurrency();
    unique_ptr<ThreadPool> thread_pool_;
} // namespace

**Comment by kimlaine** [comment]
Thanks. Fixed.
