### ISSUE TITLE
Extra semicolon warning crypto_util.c(241,2) with ,-Wextra-semi

### ISSUE THREAD

**Issue by chrdavis** [microsoft/APSI#69]
Extra ; in the below:

../../third_party/breached_password/src/msr_crypto/APSI/common/apsi/fourq/crypto_util.c(241,2): error: extra ';' outside of a function [-Werror,-Wextra-semi]
  241 | };
      |  ^

**Comment by kimlaine** [comment]
Thank you for pointing this out.
