### ISSUE TITLE
when compile apsi, use  CMake, vcpkg can't find seal, but seal is installed by vcpkg

### ISSUE THREAD

**Issue by hushanxue** [microsoft/APSI#7]
First, download vcpkg, and install  seal   using .\vcpkg install seal[no-throw-tran]:x64-windows-static-md
        and using vcpkg to install other dependency, kuku 
2nd,  vcpkg integrate install

3rd:cmake -S ../ -B . -DCMAKE_TOOLCHAIN_FILE=D:/src/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET="x64-windows-static"
---------------------------------------------------------------
Error: 
-- Building for: Visual Studio 16 2019
-- Build type (CMAKE_BUILD_TYPE): Release
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- The CXX compiler identification is MSVC 19.29.30037.0
-- The C compiler identification is MSVC 19.29.30037.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- APSI debug mode: OFF
-- APSI_USE_CXX17: ON
CMake Error at D:/src/vcpkg/scripts/buildsystems/vcpkg.cmake:771 (_find_package):
  By not providing "FindSEAL.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SEAL", but
  CMake did not find one.

  Could not find a package configuration file provided by "SEAL" (requested
  version 3.6) with any of the following names:

    SEALConfig.cmake
    seal-config.cmake

  Add the installation prefix of "SEAL" to CMAKE_PREFIX_PATH or set
  "SEAL_DIR" to a directory containing one of the above files.  If "SEAL"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:111 (find_package)

-- Configuring incomplete, errors occurred!
See also "D:/src/APSI/build/CMakeFiles/CMakeOutput.log".
----------------------------------------------------------------------------
Page [https://github.com/microsoft/APSI ] told me [ The CMake build system can then automatically find these pre-installed packages], but it not worked

**Comment by kimlaine** [comment]
The PR is now merged to vcpkg so it should work now normally.
