### ISSUE TITLE
what if the receiver want to query an item not included in the receiver's set which was preprocessed in the offline phase? 

### ISSUE THREAD

**Issue by xin2panjin** [microsoft/APSI#73]
As descripted in the paper and the README doc, all the items the receiver wants to query are needed to be preprocessed (encrypted by OPRF) in the offline phase. Does it mean that the receiver can only query the items that showed up in the preprocessing phase? If the receiver has a new item to query, how does the algorithm solve it? or it's just not supported?

**Comment by kimlaine** [comment]
Not sure I understand what you mean. The receiver can query whatever it wants, but unless the sender had inserted that item in its `SenderDB` it won't obviously show up as a match (found item). The sender can also append items to its `SenderDB` at a later point, but this is not supported by the simple example CLI. You'll have to write your own program and can use the `SenderDB::insert_or_assign` and `SenderDB::remove` functions to add and remove stuff whenever you want.
