### ISSUE TITLE
can you make a demo? I have used vcpkg to install the apsi, but understand how to use.Thanks

### ISSUE THREAD

**Issue by TY-cc** [microsoft/APSI#9]

**Comment by kimlaine** [comment]
I understand that the library is a bit complex to learn and use. If you look at the source code, you'll see that includes example sender and receiver implementations. You can build those by configuring the project with `-DAPSI_BUILD_CLI=ON`. However, this is a somewhat fancy example that provides networking and CLI and maybe a bit more than an absolute minimal viable example.

Instead, I wrote a [minimal single-file example](https://github.com/kimlaine/APSI_example) demonstrating the "advanced API" that lets you handle your own networking. Does this help?

I also noticed there are some mistakes in the README.md describing the Sender's advanced API. I'll get these fixed.
